import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/sections/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Credex Assignment",
  description: "Generated by create next app",
  keywords: "next.js, tailwind, react",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Navbar />
          {children}
          <Toaster
            position="top-right"
            offset={{
              top: 70,
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
